In [115]:
import numpy as np
import math

In [116]:
w1 = np.array([[0.3, 0.3, -0.4, 1.2],
               [-0.1, -3.1, 1.4, -2.3],
               [1.1, 0.9, 1.3, 0.8]])

w2 = np.array([[0.8, 0.7, 0.3],
              [0.5, 0.1, -0.6],
              [-0.4, 0.9, 0.7]])

wo = np.array([-0.4, 0.8, 1.2])


In [117]:
w1

array([[ 0.3,  0.3, -0.4,  1.2],
       [-0.1, -3.1,  1.4, -2.3],
       [ 1.1,  0.9,  1.3,  0.8]])

In [118]:
w2

array([[ 0.8,  0.7,  0.3],
       [ 0.5,  0.1, -0.6],
       [-0.4,  0.9,  0.7]])

In [119]:
wo

array([-0.4,  0.8,  1.2])

In [120]:
x = np.array([[1.2, 0.3, 0.9],
              [0.7, 0.1, 0.2],
              [1.5, 2.9, 1.4],
              [2.3, 1.4, 0.9]])

In [121]:
def RELU(array):
  row = array.shape[0]
  try:
    col = array.shape[1]
  except:
    col = 0

  for i in range(row):
    for j in range(col):
      if array[i, j] <= 0:
        array[i, j] = 0
  return array

<h2>problem1-2</h2>


In [122]:
O = np.tanh(np.matmul(wo, RELU(np.matmul(w2, RELU(np.matmul(w1, x))))))

In [123]:
print(O)

[0.96022594 0.99880529 0.96340055]


<h2>Problem1-3</h2>

In [124]:
def ELU(array):
  row = array.shape[0]
  try:
    col = array.shape[1]
  except:
    col = 0

  for i in range(row):
    for j in range(col):
      z = array[i][j]
      if z < 0:
        array[i, j] = math.exp(z) - 1
  return array

In [125]:
O = np.tanh(np.matmul(wo, RELU(np.matmul(w2, ELU(np.matmul(w1, x))))))

In [126]:
print(O)

[0.81846028 0.99880529 0.91271419]
